name: testing building LaTeX documents
on:
  push:
  workflow_dispatch:

jobs:
  article-and-presentaion-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTex document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: ./
          latexmk_shell_escape: true
          extra_fonts: ./fonts/SmileySans-Oblique.ttf
          root_file: |
            ./article.tex
            ./presentation.tex
          latexmk_use_xelatex: true
      - name: Check Files
        run: |
          ls -lthR
